version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: gormdb
    ports:
    - 3306:3306
    container_name: gormdb
    restart: always
    networks: 
      - rede

  gin:
    build: .
    ports:
    - 8080:8080
    container_name: gin
    image: gin
    restart: always
    networks: 
      - rede

networks:
  rede:
    driver: bridge