version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: dbDockerfile
    ports:
      - 3306:3306
    container_name: mysqldb
    image: mysqldb
    restart: always
    networks:
      - rede

  flask:
    build:
      context: .
      dockerfile: flaskDockerfile
    depends_on:
      - mysql
    ports:
      - 5000:5000
    container_name: flask
    image: flask
    restart: always
    networks:
      - rede

networks:
  rede:
    driver: bridge
